### ISSUE TITLE
why the below crash first time and sometimes it works? i have no idea what went wrong

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#162]
given the information below, can u have a clue / hint why the below error exist?
sometimes the program run without issues when first ran but if first ran is not successful, the below error will show and it will show always.
```
2022/12/24 09:42:50 Xsfh1 = *rueidis.singleClient
2022/12/24 09:42:50 s123fdsd = &{%!s(*rueidis.mux=&{<nil> 0xc0000387e0 [{0xc000038380} {<nil>} {<nil>} {<nil>}] [<nil> <nil> <nil> <nil>] [{0 0} {0 0} {0 0} {0 0}] 0xc0000a2730 0xe57e60 127.0.0.1:906}) %!s(uint32=0) {%!s(uint16=32768)} %!s(bool=true)}
2022/12/24 09:42:50 ERRio121 = {%!s(*cmds.CommandSlice=&{[���
172.17.0.2%]}) %!s(uint16=0) %!s(uint16=32768)} = &{%!s(*rueidis.mux=&{<nil> 0xc0000387e0 [{0xc000038380} {<nil>} {<nil>} {<nil>}] [<nil> <nil> <nil> <nil>] [{0 0} {0 0} {0 0} {0 0}] 0xc0000a2730 0xe57e60 127.0.0.1:906}) %!s(uint32=0) {%!s(uint16=32768)} %!s(bool=true)}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe5eed3]

goroutine 55 [running]:
example.com/examplego/db/util/rueidis.(*pipe).Do(0xc000038380, {0x0, 0x0}, {0xc00058ca98, 0x0, 0x8000})
        /root/go/pkg/mod/example.com/examplego/db/util/rueidis@v0.0.0-20221223194253-9dbe97f4794b/pipe.go:669 +0x93
example.com/examplego/db/util/rueidis.(*mux).pipeline(0xc000021830, {0x0, 0x0}, {0xc00058ca98, 0x0, 0x8000})
        /root/go/pkg/mod/example.com/examplego/db/util/rueidis@v0.0.0-20221223194253-9dbe97f4794b/mux.go:197 +0xda
example.com/examplego/db/util/rueidis.(*mux).Do(0x0?, {0x0?, 0x0?}, {0xc00058ca98, 0x0, 0x8000})
        /root/go/pkg/mod/example.com/examplego/db/util/rueidis@v0.0.0-20221223194253-9dbe97f4794b/mux.go:154 +0xd3
example.com/examplego/db/util/rueidis.(*singleClient).Do(0xc00058ca50, {0x0, 0x0}, {0xc00058ca98, 0x0, 0x8000})
        /root/go/pkg/mod/example.com/examplego/db/util/rueidis@v0.0.0-20221223194253-9dbe97f4794b/client.go:41 +0xb7
example.com/examplego/net/http2/frwll.ProxyHandlerHertz({0x11af04f?, 0xa?}, 0xc00062a680)
```

extracted from main.go
```
type Cpool struct {
	mu sync.Mutex
	cm map[uint16]rueidis.Client
}

func (item Cpool) NewInstance() Cpool {
	item.cm = make(map[uint16]rueidis.Client)
	return item
}

func (p *Cpool) Get(addrIndex uint16) (c rueidis.Client, err error) {
	p.mu.Lock()
	addr := B2s(CredisAddrCache.Get(nil, Uint16ToBytes(addrIndex)))
	if c = p.cm[addrIndex]; c == nil {
		if c, err = rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{addr}, DisableCache: true}); err == nil {
			log.Printf("Xsfh1 = %T", c)
			p.cm[addrIndex] = c
		}
		if err != nil {
			log.Printf("err1e9 = %s", err)
		}
	}
	log.Printf("s123fdsd = %s", c)
	p.mu.Unlock()
	return
}

var (
	Credises Cpool
)

func init() {
	Credises = Cpool{}.NewInstance()
}


func main()
                   // ... an extract of sample code.
			credis, err := Credises.Get(uint16(iX))
			if err != nil {
				log.Printf("credisErr = %s", err)
			}

			var ctxRedis context.Context

			fwData := credis.B().Arbitrary(rueidis.BinaryString(fwRes)).Build() // <- this is fine... BUT...
			
			log.Printf("ERRio121 = %s = %s", fwData, credis)
			ioReaderData, err := credis.Do(ctxRedis, fwData).AsReader() //<- crashed here
```

**Comment by rueian** [comment]
> var ctxRedis context.Context

This ctxRedis can't be nil.

**Comment by ultperf** [comment]
@rueian thx for helping. what should it be then? what value should i give it?
