### ISSUE TITLE
Panic on `RedisResult.AsStrMap()`

### ISSUE THREAD

**Issue by Delicious-Bacon** [rueian/rueidis#61]
My project panics when I use `RedisResult.AsStrMap()`

Here are the outputs:
```
panic: runtime error: index out of range [21] with length 21

goroutine 1 [running]:
github.com/rueian/rueidis.(*RedisMessage).AsStrMap(0xc00037f890?)
        /home/user/go/pkg/mod/github.com/rueian/rueidis@v0.0.60/message.go:573 +0x206
github.com/rueian/rueidis.RedisResult.AsStrMap({{0x0, 0x0}, {0x2a, {0x0, 0x0}, {0xc0001f1600, 0x15, 0x15}, 0x0, 0x0}})
        /home/user/go/pkg/mod/github.com/rueian/rueidis@v0.0.60/message.go:246 +0x11f
main.main()
        /home/user/working/Game-for-the-buck/main.go:122 +0xe3b
exit status 2
```

This is the line:
https://github.com/rueian/rueidis/blob/f2c082a144ea6b762485b9320035ea2d7f169ab2/message.go#L573

It's probably due to fixed length of the map and some rounding:
```
r := make(map[string]string, len(m.values)/2)
```

Let me know if you need more info.

**Comment by rueian** [comment]
Hi @Delicious-Bacon,

Thank you for reporting this. However, the way to fix this will be adding a odd length check and panicking

**Comment by rueian** [comment]
> Not sure if that's the proper way, but it worked like that. 🤷

It really depends on what command you sent. Can you share the full command?

> or I can immediately call the commands as shown in [bulk operations](https://github.com/rueian/rueidis#bulk-operations)

Yes, you can. You should use MULTI EXEC only when you need the atomic execution provided by them.

**Comment by Delicious-Bacon** [comment]
> It really depends on what command you sent. Can you share the full command?

Sure, it's something like this, but uses `FT.SEARCH`:

```
// dedicate for MULTI
cd, cancel := c.Dedicate()
defer cancel()

var cmds rueidis.Commands

for _, itemID := range itemIDs {
    cmds = append(
        cmds,
        cd.B().
            FtSearch().Index("items").
            Query("@cc:{"+countryID+"}"+" @id:{"+itemID+"} @u:[5 10]").
            Limit().OffsetNum(0, 1).Build(),
    )
}

for _, res := range cd.DoMulti(ctx, cmds...) {
    if err := res.Error(); err != nil {
        if rueidis.IsRedisNil(err) {
            continue
        }
        return nil, fmt.Errorf("failed on MULTI command: %w", err)
    }

    r, err := res.ToArray()
    if err != nil {
        return nil, err
    }
    if len(r) <= 1 { // hacky way to check if the result is empty
        continue
    }

    rm, err := r[2].AsStrMap() // the third element is the result
    if err != nil {
        return nil, err
    }

    var item item.Item
    err = json.Unmarshal([]byte(rm["$"]), &item) // $ is the result
    if err != nil {
        return nil, err
    }
```

And while we're at it, is there a way to do `REDUCE FIRST_EXAMPLE 4 @property BY ASC/DESC`? I can chain up to `@property`, but I lack the command `BY` and `ASC/DESC` like [this example](https://redis.io/docs/stack/search/reference/aggregations/#first_value).

```
client.B().FtAggregate().Index("items").
    Query("*").Load("1").Field("@__key").
    Groupby(1).Property("@title").
    Reduce("FIRST_VALUE").Nargs(4).Arg("@__key").By("@rating").DESC() // missing BY
```

**Comment by rueian** [comment]
> And while we're at it, is there a way to do `REDUCE FIRST_EXAMPLE 4 @property BY ASC/DESC`? I can chain up to `@property`, but I lack the command `BY` and `ASC/DESC` like [this example](https://redis.io/docs/stack/search/reference/aggregations/#first_value).

Unfortunately, no. The command `BY` is absent from the source commands.json: https://github.com/RediSearch/RediSearch/blob/master/commands.json#L1197-L1218

But I will add it to rueidis manually tomorrow.

**Comment by Delicious-Bacon** [comment]
Cheers to that! 🥂 

By the way, you [asked](https://github.com/rueian/rueidis/issues/61#issuecomment-1185699226):
>> Not sure if that's the proper way, but it worked like that. 🤷

> It really depends on what command you sent. Can you share the full command?

Was there anything I could have done differently there?

**Comment by rueian** [comment]
> Was there anything I could have done differently there?

Here are two examples from the `om` pacakge:
1. https://github.com/rueian/rueidis/blob/a7c926da198d791b938295a103ff208c66db36be/om/json.go#L116-L134
2. https://github.com/rueian/rueidis/blob/a7c926da198d791b938295a103ff208c66db36be/om/hash.go#L114-L129

They are similar to what you have done here. I think I could make a function available to `RedisResult` to do a similar thing.

**Comment by rueian** [comment]
Hi @Delicious-Bacon,

```golang
client.B().FtAggregate().Index("items").
    Query("*").Load("1").Field("@__key").
    Groupby(1).Property("@title").
    Reduce("FIRST_VALUE").Nargs(4).Arg("@__key").By("@rating").Desc()
```

should works in v0.0.63.

**Comment by Delicious-Bacon** [comment]
Hey, @rueian !

>Here are two examples from the om pacakge:

&&

>Reduce("FIRST_VALUE").Nargs(4).Arg("@__key").By("@rating").Desc()

Thank you! 💯 🙇‍♂️ 🙇‍♂️ 

Your package is the best Redis experience I've had. I love your colossal efforts! 🥇
