### ISSUE TITLE
Panic on `rdb.Do` when there's redis is not up.

### ISSUE THREAD

**Issue by zhiburt** [rueian/rueidis#80]
Hi there
I've just noticed this behavior I guess it's not suppose to be the case as we return error?

```go

	rdb, _ := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	defer rdb.Close()

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()

	err := rdb.Do(ctx, rdb.B().Ping().Build()).Error()
	if err != nil {
		log.Fatal("[redis] ping was not successfull", zap.Error(err))
	}
```

```log
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cddee]

goroutine 1 [running]:
github.com/rueian/rueidis.(*clusterClient).Close(0x0)
        /github.com/rueian/rueidis@v0.0.70/cluster.go:580 +0x2e
panic({0x6df000, 0x9e1540})
        /usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/rueian/rueidis.(*clusterClient).B(0x7cf150?)
        /github.com/rueian/rueidis@v0.0.70/cluster.go:255
main.main()
        /main.go:61 +0x1ef
exit status 2
```

Take care

**Comment by rueian** [comment]
Hi @zhiburt,

The error return from the `rueidis.NewClient` should be check first.
```
rdb, err := rueidis.NewClient(rueidis.ClientOption{
	InitAddress: []string{"127.0.0.1:6379"},
})
if err != nil {
	panic(err)
}
```

**Comment by zhiburt** [comment]
I see;
Sorry it was my fault then.

Thank for the answer and take care.
